# Generated by Django 3.0.8 on 2020-07-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('task_type', models.IntegerField(choices=[(0, 'classification')])),
                ('api_url', models.CharField(max_length=100)),
            ],
        ),
    ]
