# Generated by Django 3.0.8 on 2020-07-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='task_type',
            field=models.IntegerField(choices=[(1, 'image_only'), (2, 'classification')]),
        ),
    ]
